version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn financial.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/api
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
volumes:
  postgres_data:
