version: "3.9"
services:
  web:
    build: .
    command: uvicorn financial.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=python_assignment
volumes:
  postgres_data:
